# Generated by Django 4.0.4 on 2022-05-18 19:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_mig6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('No Author', 'No Author'), ('test', 'test'), ('test4', 'test4'), ('test1', 'test1'), ('test3', 'test3'), ('test5', 'test5'), ('test2', 'test2')], default='No_Author', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 28, 56, 979120)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 28, 56, 979120)),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('group2', 'group2'), ('group1', 'group1'), ('default', 'default'), ('group3', 'group3'), ('all', 'all')], default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PROG', 'In Progress'), ('DONE', 'Done'), ('TODO', 'To Do'), ('TEST', 'In Testing')], default='TODO', max_length=4),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 28, 56, 993050)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 28, 56, 993050)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f6807937-6efd-45ee-839d-ebcfad41f7d8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
