# Generated by Django 4.0.4 on 2022-05-18 19:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_mig7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(choices=[('test4', 'test4'), ('test3', 'test3'), ('test', 'test'), ('test5', 'test5'), ('test2', 'test2'), ('test1', 'test1'), ('No Author', 'No Author')], default='No_Author', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 38, 26, 637579)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 38, 26, 637579)),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.CharField(choices=[('group1', 'group1'), ('group2', 'group2'), ('group3', 'group3'), ('default', 'default')], default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('PROG', 'In Progress'), ('DONE', 'Done'), ('TEST', 'In Testing')], default='TODO', max_length=4),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 38, 26, 653535)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 21, 38, 26, 653535)),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9278fb97-355d-4e2f-b123-57c1f62d4971'), editable=False, primary_key=True, serialize=False),
        ),
    ]
